### ISSUE TITLE
observer problem in section  7

### ISSUE THREAD

**Issue by zakariabijoy** [TryCatchLearn/Reactivities_2.2#18]
observer does not observer activitiesStore

**Comment by luaandv** [comment]
> 
> 
> observer does not observer activitiesStore

me too

**Comment by zakariabijoy** [comment]
> > observer does not observer activitiesStore
> 
> me too

https://mobx.js.org/react-integration.html    -- follow this 
 .. decorators is not working with the latest version  of  mobx
